export const products = [
  {
    id: "bag-001",
    name: "Designer Clutch",
    category: "Handbags",
    price: 3999,
    image: "/products/handbags/designer-clutch.jpeg",
    description: "Elegant designer clutch perfect for special occasions.",
  },
  {
    id: "saree-001",
    name: "Crunchu Multi Saree Party Wear",
    category: "Sarees",
    price: 1299,
    image: "/products/sarees/pink-saree.jpeg",
    description: "Beautiful pink saree.",
  },
  {
    id: "saree-002",
    name: "Rangoli Crush Saree",
    category: "Sarees",
    price: 899,
    image: "/products/sarees/red-saree.jpeg",
    description: "Traditional red silk saree.",
  },
  {
    id: "kurti-001",
    name: "Mayuri Salwar Suit Set",
    category: "Kurtis",
    price: 1650,
    image: "/products/kurtis/cotton-kurti1.jpeg",
    description: "Premium cotton kurti.",
  },
  {
    id: "kurti-002",
    name: "Premium Cotton Kurti Pant with Dupatta Set",
    category: "Kurtis",
    price: 1149,
    image: "/products/kurtis/cotton-kurti2.jpeg",
    description: "Beautiful cotton kurti set.",
  },
  {
    id: "kurti-003",
    name: "Mal Mal Cotton Printed Kurti Set",
    category: "Kurtis",
    price: 1099,
    image: "/products/kurtis/cotton-kurti3.jpeg",
    description: "Embroidered cotton kurti.",
  },
  {
    id: "kids-001",
    name: "Baby Lehanga Gold",
    category: "Kids Wear",
    price: 1349,
    image: "/products/kids/baby-lehanga-gold.jpeg",
    description: "Beautiful baby lehanga.",
  },
  {
    id: "kids-002",
    name: "Kids Long Frock with Over Coat",
    category: "Kids Wear",
    price: 1149,
    image: "/products/kids/kids-gown1.jpeg",
    description: "Designer kids gown.",
  },
  {
    id: "kids-003",
    name: "Kids Lehenga",
    category: "Kids Wear",
    price: 1399,
    image: "/products/kids/kids-lehenga1.jpeg",
    description: "Festive kids lehenga.",
  },
  {
    id: "jewel-001",
    name: "Diamond Earrings",
    category: "Jewellery",
    price: 899,
    image: "/products/jewellery/diamond-earrings.jpeg",
    description: "Beautiful diamond earrings.",
  },
  {
    id: "jewel-002",
    name: "Diamond Necklace",
    category: "Jewellery",
    price: 1999,
    image: "/products/jewellery/diamond-necklace.jpeg",
    description: "Elegant diamond necklace.",
  },
  {
    id: "jewel-003",
    name: "Gold Long Chain",
    category: "Jewellery",
    price: 1599,
    image: "/products/jewellery/gold-long-chain.jpeg",
    description: "Traditional gold long chain.",
  },
  {
    id: "jewel-004",
    name: "Gold Necklace",
    category: "Jewellery",
    price: 1899,
    image: "/products/jewellery/gold-necklace.jpeg",
    description: "Beautiful gold necklace.",
  },
  {
    id: "jewel-005",
    name: "Gold Peacock Earrings",
    category: "Jewellery",
    price: 999,
    image: "/products/jewellery/gold-peacock-earrings.jpeg",
    description: "Peacock design earrings.",
  },
  {
    id: "jewel-006",
    name: "Hip Belt 1",
    category: "Jewellery",
    price: 1299,
    image: "/products/jewellery/hip-belt1.jpeg",
    description: "Traditional hip belt.",
  },
  {
    id: "jewel-007",
    name: "Hip Belt 2",
    category: "Jewellery",
    price: 1299,
    image: "/products/jewellery/hip-belt2.jpeg",
    description: "Traditional hip belt.",
  },
  {
    id: "jewel-008",
    name: "Pearl Earrings 1",
    category: "Jewellery",
    price: 799,
    image: "/products/jewellery/pearl-earrings1.jpeg",
    description: "Elegant pearl earrings.",
  },
  {
    id: "jewel-009",
    name: "Pearl Earrings 2",
    category: "Jewellery",
    price: 799,
    image: "/products/jewellery/pearl-earrings2.jpeg",
    description: "Elegant pearl earrings.",
  },
  {
    id: "jewel-010",
    name: "Pink Bangles",
    category: "Jewellery",
    price: 699,
    image: "/products/jewellery/pink-bangles.jpeg",
    description: "Designer pink bangles.",
  },
  {
    id: "jewel-011",
    name: "Silver Bracelet",
    category: "Jewellery",
    price: 899,
    image: "/products/jewellery/silver-bracelet.jpeg",
    description: "Classic silver bracelet.",
  },
];

export type Product = (typeof products)[number];